NSString *const LAST_OPENED_PROJECT_PATH = @"LAST_OPENED_PROJECT_PATH";
NSString *const LAST_VISIT_LEFT_PANEL_VISIBLE = @"LAST_VISIT_LEFT_PANEL_VISIBLE";
NSString *const LAST_VISIT_BOTTOM_PANEL_VISIBLE = @"LAST_VISIT_BOTTOM_PANEL_VISIBLE";
NSString *const LAST_VISIT_RIGHT_PANEL_VISIBLE = @"LAST_VISIT_RIGHT_PANEL_VISIBLE";

NSString *const SHOW_EXTRAS = @"SHOW_EXTRAS";
NSString *const SHOW_GUIDES = @"SHOW_GUIDES";
NSString *const SHOW_GUIDE_GRID = @"SHOW_GUIDE_GRID";
NSString *const SHOW_STICKY_NOTES = @"SHOW_STICKY_NOTES";

NSString *const SNAP_TOGGLE = @"SNAP_TOGGLE";
NSString *const SNAP_TOGUIDES = @"SNAP_TOGUIDES";
NSString *const SNAP_GRID = @"SNAP_GRID";
NSString *const SNAP_NODE = @"SNAP_NODE";
